services:
  vigil:
    build: .
    container_name: vigil
    restart: unless-stopped
    env_file: .env
    volumes:
      - /volume1/vigil-download:/downloads
      - ./data:/app/data
    ports:
      - "5005:5005" # Match the internal port 5005
    deploy:
      resources:
        limits:
          memory: 384M
  